### ISSUE TITLE
Avoid using pesy in build environment for the time being

### ISSUE THREAD

**Issue by ManasJayanth** [jchavarri/rebez#4]
Rebez uses `pesy` to build the project and caused Revery's build to fail on Windows

```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: rebez@github:jchavarri/rebez#46cbc183
    # esy-build-package: pwd: C:\Users\bryphe\.esy\source\i\rebez__4ce958a8
    # esy-build-package: running: "pesy"

    rebez@0.0.1

      Almost there! We just need to prepare a couple of files:

        □  Update test/dune build config
        □  Update library/dune build config
        □  Update executable/dune build config

      To perform those updates and build run:

        esy pesy



    error: command failed: "pesy" (exited with 1)
    esy-build-package: exiting with errors above...

  building rebez@github:jchavarri/rebez#46cbc183
```

This is probably due to stale dune files: pesy must have marked dune files as stale after it updated. But the problem can be avoided by using pesy a bit differently.

Pesy is right now caught in between being a build tool and a config manager. It doesn't function to it full potential as a build tool as it doesn't work closely with dune enough (for instance it is forced to create dune files in source). So it's best left to just manage config for you.

This means, we now use `pesy` only to generated config files for the project (dune and CI). We can now move `pesy` to devDependencies, thereby ensuring packages that consume `rebez` don't have to pull `pesy`.

This was not your fault. We will update Pesy's README to reflect this workflow. I'll be more happy to raise a PR and fix this for you if you think it okay 🙂

**Comment by ManasJayanth** [comment]
This being said, the dune files probably need some attention too.

**Comment by jchavarri** [comment]
thanks @prometheansacrifice!

So, the fix as I understand would be to either move `pesy` to `devDependencies` or just "eject" pesy and use `dune` from now? (I feel inclined to do # 2, just used pesy as an experiment in this PR but generally use just dune for other projects).

>  the dune files probably need some attention too.

Could you elaborate, please?

**Comment by ManasJayanth** [comment]
> Could you elaborate, please?

I suspect the dune files are stale wrt a new pesy. But I'm not sure. I'll clone and repo and see if understand the cause

> So, the fix as I understand would be to either move pesy to devDependencies or just "eject" pesy and use dune from now

Moving it to devDependencies, using `dune build -p #{self.name}` (instead of `pesy`) as the build step will suffice. esy also supports `buildDev`. Ideally, that should be `pesy` so that you can catch stale dune files.

**Comment by jordwalke** [comment]
Here's what I changed in pesy to make sure all new projects have the optimal configuration:
https://github.com/jordwalke/pesy/commit/b8b4600eb932438c62b00c1164aa61a967d67bdb

**Comment by jordwalke** [comment]
By adjusting your config to match what pesy now emits by default for all new projects, it effectively does eject to pure dune when depended on by others, but while developing locally you can still use `pesy` to update your build config. This way there's no downside to using pesy - it adds no burden to dependers. When I started pesy we esy didn't have the feature of `buildDev` and `build` - so it wasn't an option.
